name: Pipeline CI/CD
run-name: Pipeline CI/CD executada por ${{ github.actor }} em ${{ github.run_number }}
on:
  workflow_dispatch:
  push:
    branches:
      -  main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      -  name: Obtendo o código do projeto
         uses: actions/checkout@v4
      -  name: Análise do Docker file
         uses: hadolint/hadolint-action@v3.1.0
         with:
          dockerfile: ./src/Review-Filmes.Web/Dockerfile
      -  name: Setup dotnet
         uses: actions/setup-dotnet@v4
         with:
           dotnet-version: "8.0.300"
      -  name: Execução do comando build
         working-directory: ./src
         run: dotnet build Review-Filmes.sln
  testes:
    needs: [build]
    uses: joaohfm86/desafio-cicd-01/.github/workflows/testes.yml@main
    secrets: inherit
  release:
    name: Criação de Release
    runs-on: ubuntu-latest
    needs: [testes]
    steps:
      -  name: Obtendo o código do projeto
         uses: actions/checkout@v4
      -  name: Efetuando o login do Docker Hub
         uses: docker/login-action@v3
         with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      -  name: Build e push da imagem docker
         uses: docker/build-push-action@v6
         with:
          push: true
          context: ./src
          file: ./src/Review-Filmes.Web/Dockerfile
          tags: |
            joaohfm/projeto-devops-pro:latest
            joaohfm/projeto-devops-pro:v${{ github.run_number }}
      -  name: Executar o Trivy
         uses: aquasecurity/trivy-action@0.23.0
         with:
          scan-type: 'image'
          image-ref: joaohfm/projeto-devops-pro:v${{ github.run_number }}
          format: sarif
          output: trivy-docker-result.sarif
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
      -  name: Upload do arquivo trivy para o github
         uses: github/codeql-action/upload-sarif@v3
         with:
          category: docker-result
          sarif_file: trivy-docker-result.sarif 
  Deploy-homologacao:
    needs: [release]
    uses: joaohfm86/desafio-cicd-01/.github/workflows/deploy.yml@main
    secrets: inherit
        

